version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.23.0
    - 5.24.0
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.0
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: karma-sauce-launcher
    versions:
    - 4.3.5
